image: ghcr.io/home-assistant/{arch}-hassio-multicast
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/plugin-multicast/.*
args:
  MDNS_REPEATER_VERSION: 1.2.0
labels:
  io.hass.type: multicast
  org.opencontainers.image.title: Home Assistant Multicast Plugin
  org.opencontainers.image.description: Home Assistant Supervisor plugin for Multicast
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-multicast
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
