image: ghcr.io/home-assistant/{arch}-hassio-multicast
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.17
  armhf: ghcr.io/home-assistant/armhf-base:3.17
  armv7: ghcr.io/home-assistant/armv7-base:3.17
  amd64: ghcr.io/home-assistant/amd64-base:3.17
  i386: ghcr.io/home-assistant/i386-base:3.17
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/plugin-multicast/.*
args:
  MDNS_REPEATER_VERSION: 1.2.0
labels:
  io.hass.type: multicast
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-multicast
