image: homeassistant/{arch}-hassio-multicast
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.13
  armhf: ghcr.io/home-assistant/armhf-base:3.13
  armv7: ghcr.io/home-assistant/armv7-base:3.13
  amd64: ghcr.io/home-assistant/amd64-base:3.13
  i386: ghcr.io/home-assistant/i386-base:3.13
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  MDNS_REPEATER_VERSION: 1.2.0
labels:
  io.hass.type: multicast
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-multicast
